### ISSUE TITLE
Definição da UI e UX

### ISSUE THREAD

**Issue by victorhfsilva** [START-DB-2023/ScrumTracker#1]

**Comment by ChaiCaroline** [comment]
![image](https://github.com/START-DB-2023/ScrumTracker/assets/117395143/4377c37d-49b2-4579-a89c-aaba506060e0)

Layout tela inicial - login do usuário.

**Comment by CaiquePrado** [comment]
![home](https://github.com/START-DB-2023/ScrumTracker/assets/121769123/a1a7a3a6-6b83-4c93-9b37-01cb1e1dc8d2)

**Comment by ajuliamm** [comment]
![image](https://github.com/START-DB-2023/ScrumTracker/assets/93016620/02c16a39-e605-4160-ab9f-580aa0ddf8a2)

**Comment by victorhfsilva** [comment]
![image](https://github.com/START-DB-2023/ScrumTracker/assets/22583145/4af2d7f5-e405-465a-8301-17bb3cd0c01f)
